version: '2.4'
services:
  caselist-client:
    image: caselist-client:latest
    container_name: caselist-client
    restart: always
    ports:
        - 5836:5836
    volumes:
        - /net/configs/caselist/client/production.env:/app/.env.production