version: '2.4'
services:
  solr:
    image: solr:latest
    container_name: solr
    restart: always
    ports: 
      - 8983:8983
    volumes:
      - ${SOLR_DIR:-/var/solr}:/var/solr
    command:
      - solr-precreate
      - caselist
  tika:
    image: apache/tika:latest
    container_name: tika
    restart: always
    ports:
        - 9998:9998