version: '2.4'
services:
  api:
    image: caselist_server:latest
    container_name: caselist_server
    restart: always
    network_mode: "host"
    volumes:
        - /net/configs/caselist/server/production.env:/api/.env
  api-swagger:
    image: swaggerapi/swagger-ui
    container_name: api-swagger
    restart: always
    ports:
        - 10010:8080
    environment:
        URL: https://api.opencaselist.com/v1/docs