version: '2.4'
services:
  api:
    image: caselist_server:latest
    container_name: caselist_server
    restart: always
    ports:
        - 5834:5834
    volumes:
        - /net/configs/caselist/server/production.env:/api/.env
        - /var/www/caselist:/api/uploads
  api-swagger:
    image: swaggerapi/swagger-ui
    container_name: caselist_swagger
    restart: always
    ports:
        - 5835:8080
    environment:
        URL: https://api.opencaselist.com/v1/docs