name: caselist CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    CI: true
    TZ: "America/Chicago"
    Succeeded: ":white_check_mark: "
    SLACK_ICON: ":octocat:"
    SLACK_CHANNEL: "#tech-updates"
    SLACK_USERNAME: "Github Actions"
    SLACK_COLOR: "#de4e2b"
    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    SLACK_TITLE: ":heavy_multiplication_x:"
    SLACK_FOOTER: "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks|[caselist:main]>"
    MSG_MINIMAL: true

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get node
      uses: actions/setup-node@v1
      with:
        node-version: 18.2.0

    - name: Install packages
      run: |
        cd client && npm install

    - name: Lint
      run: |
        cd client && npm run lint

    - name: Test
      run: |
        cd client && npm run test

    - name: If tests passed change SLACK_COLOR and SLACK_TITLE accordingly
      if: success()
      run: |
        echo "SLACK_COLOR=good" >> $GITHUB_ENV
        echo "SLACK_TITLE=${{ env.Succeeded }}" >> $GITHUB_ENV

    - name: Send slack notification
      if: always()
      uses: rtCamp/action-slack-notify@v2.1.0

  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get node
      uses: actions/setup-node@v1
      with:
        node-version: 18.2.0

    - name: Install packages
      run: |
        cd server && npm install

    - name: Lint
      run: |
        cd server && npm run lint

    - name: Test
      run: |
        cd server && npm run test

    - name: If tests passed change SLACK_COLOR and SLACK_TITLE accordingly
      if: success()
      run: |
        echo "SLACK_COLOR=good" >> $GITHUB_ENV
        echo "SLACK_TITLE=${{ env.Succeeded }}" >> $GITHUB_ENV

    - name: Send slack notification
      if: always()
      uses: rtCamp/action-slack-notify@v2.1.0
